import {DATA} from './data.js';
import {esc,num,money,compact,seconds,scatter,lines,bars,radar} from './charts.js';
const $=s=>document.querySelector(s), families=DATA.families, mainFamilies=families.filter(f=>!f.legacy), efforts=['none','low','medium','high','xhigh','max'], labels=efforts.map(e=>e==='xhigh'?'Xhigh':e[0].toUpperCase()+e.slice(1)), modelMap=new Map(DATA.models.map(r=>[r.id,r]));
const state={selected:new Set(mainFamilies.map(f=>f.id)),view:'overview',scatterMetric:'cost',log:true,overviewEffort:'medium',effortMetric:'aa',econEffort:'max',tokenEffort:'max',benchEffort:'max',benchKey:'terminalbench-4-0',tableEffort:'all',tableCategory:'core',sort:'aa',sortDir:-1,compareA:'gpt-6-1-sol-medium',compareB:'gpt-6-sol',detailModel:'gpt-6-1-sol',inspector:'gpt-6-1-sol-medium',launchIndex:0,launchView:'cost',input:100000,cache:90,output:10000,calls:100,service:'standard',capEffort:'max',priorMetric:'aa'};
const navItems=[['overview','Overview','M4 19v-5m6 5V9m6 10V4m4 15H2'],['scaling','Effort scaling','m3 17 5-6 4 3 8-10m-5 0h5v5'],['economics','Economics','M20 6c0 2-4 4-8 4S4 8 4 6s4-4 8-4 8 2 8 4Zm0 0v12c0 2-4 4-8 4s-8-2-8-4V6m0 6c0 2 4 4 8 4s8-2 8-4'],['tokens','Tokens & latency','M12 8v5l4 2M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z'],['benchmarks','Benchmarks','M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z'],['compare','Head to head','M8 3h8v9a4 4 0 0 1-8 0V3Zm0 2H4v4a4 4 0 0 0 4 4m8-8h4v4a4 4 0 0 1-4 4M12 16v5m-4 0h8'],['launch','Launch evals','M9 3h6m-5 0v6L4 20h16L14 9V3m-7 11h10'],['data','All data','M20 6c0 2-4 4-8 4S4 8 4 6s4-4 8-4 8 2 8 4Zm0 0v12c0 2-4 4-8 4s-8-2-8-4V6m0 6c0 2 4 4 8 4s8-2 8-4'],['sources','Sources','M5 3h9l5 5v13H5V3Zm9 0v6h5']];
const titles={overview:['Intelligence has a price.','Every effort. Every trade-off.'],scaling:['A better staircase.','What extra thinking actually buys you.'],economics:['Follow the money.','Per task, per run, per token.'],tokens:['Thinking takes time.','Reasoning, answers, throughput, and the wait before either.'],benchmarks:['Look beneath the index.','The same headline score can hide very different strengths.'],compare:['Put them head to head.','Pick any two models and effort levels.'],launch:['The 6.1 launch, unpacked.','OpenAI’s evaluations, kept separate from AA’s independent runs.'],data:['Every number, in one place.','Complete tables, per-benchmark economics, and downloadable data.'],sources:['Where the numbers come from.','Sources, definitions, missing results, and the limits of each comparison.']};
let chartJobs=[],chartId=0;
const available=()=>DATA.models.filter(r=>state.selected.has(r.family));
const rowsAt=e=>available().filter(r=>e==='all'||r.effort===e).sort((a,b)=>families.findIndex(f=>f.id===a.family)-families.findIndex(f=>f.id===b.family)||efforts.indexOf(a.effort)-efforts.indexOf(b.effort));
const row=(family,effort)=>DATA.models.find(r=>r.family===family&&r.effort===effort);
const dot=c=>`<i class="dot" style="--c:${c}"></i>`;
const legend=ss=>`<div class="legend">${ss.map(s=>`<span>${dot(s.color)}${esc(s.name??s.label)}</span>`).join('')}</div>`;
function select(key,opts){return `<select id="${key}" data-state="${key}" aria-label="${key.replace(/[A-Z]/g,' $&')}">${opts.map(o=>{let [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(state[key])===String(v)?'selected':''}>${esc(l)}</option>`}).join('')}</select>`}
const effortOpts=(all=false)=>[...(all?[['all','All efforts']]:[]),...efforts.map((e,i)=>[e,labels[i]])];
function chart(draw){const id='chart-'+chartId++;chartJobs.push(()=>draw($('#'+id)));return `<div class="chart" id="${id}"></div>`}
const panel=(title,desc,body,ctrl='',classes='')=>`<section class="panel ${classes}"><div class="panel-head"><div><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div>${ctrl?`<div class="controls tight">${ctrl}</div>`:''}</div>${body}</section>`;
const section=(title,sub='')=>`<div class="section-label"><h2>${title}</h2><p>${sub}</p></div>`;
const stat=(value,label,note,color)=>`<div class="stat" style="--c:${color}"><strong>${value}</strong><span>${label}</span><small>${note}</small></div>`;
const bf=(key,v)=>{const b=DATA.benchmarks.find(x=>x.key===key);return v==null?'—':num(v,b?.unit==='Elo'?0:1)+(b?.unit==='%'?'%':'')};
const prettyEffort=e=>labels[efforts.indexOf(e)]??e;
function seriesFor(metric='aa',rs=available(),categorical=false){return families.filter(f=>rs.some(r=>r.family===f.id)).map(f=>({name:f.name,color:f.color,points:rs.filter(r=>r.family===f.id).sort((a,b)=>efforts.indexOf(a.effort)-efforts.indexOf(b.effort)).map(r=>({x:categorical?efforts.indexOf(r.effort):r[metric],y:r.aa,id:r.id,tip:`${r.model} · ${prettyEffort(r.effort)}\nAA: ${r.aa??'not available'} (${num(r.aaExact,2)} unrounded)\nCost: ${money(r.cost)}/task\nOutput: ${compact(r.output)} · reasoning: ${compact(r.reasoning)}\nFirst answer: ${seconds(r.firstAnswer)}\nDecode time: ${seconds(r.decode)}`}))}))}
const coreCols=[['model','Model'],['effort','Effort'],['aa','AA'],['cost','$/task'],['totalCost','Full AA cost'],['output','Output/task'],['reasoning','Reasoning/task'],['answer','Answer/task'],['totalOutput','Full output'],['speed','Tokens/s'],['ttft','TTFT'],['firstAnswer','First answer'],['e2e','500-token E2E'],['decode','Decode/task']];
function cell(r,key){let v=r[key];if(key==='model')return r.id?`<button class="table-name" data-compare-model="${r.id}">${dot(r.color)} ${esc(r.model)}</button>`:`${dot(r.color)} ${esc(r.model)}`;if(key==='effort')return prettyEffort(v);if(['inputPrice','cachePrice','outputPrice','cacheWritePrice','blendedPrice'].includes(key))return v==null?'—':'$'+num(v,v<1?3:2);if(['cost','totalCost'].includes(key))return money(v);if(['output','reasoning','answer','totalOutput','totalInput','totalReasoning','totalAnswer','contextAA'].includes(key))return compact(v);if(['ttft','firstAnswer','e2e','decode'].includes(key))return seconds(v);return v==null?'—':num(v,key==='aa'?0:1)}
function table(rs,cols=coreCols,sortable=false){return `<div class="table-wrap"><table><thead><tr>${cols.map(([k,l])=>`<th>${sortable?`<button class="sort-button" data-sort="${k}">${l}${state.sort===k?(state.sortDir===1?' ↑':' ↓'):''}</button>`:l}</th>`).join('')}</tr></thead><tbody>${rs.length?rs.map(r=>`<tr class="${r.family==='gpt-6-1-sol'?'highlight':''}">${cols.map(([k])=>`<td class="${k==='model'?'model-cell':''}">${cell(r,k)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">No models selected.</td></tr>`}</tbody></table></div>`}
function inspector(){let r=modelMap.get(state.inspector);return `<div class="point-inspector" id="point-inspector"><div><span>Selected point · click any dot</span><strong style="color:${r.color}">${r.model} · ${prettyEffort(r.effort)}</strong></div><div><span>AA Index</span><strong>${r.aa??'—'}</strong></div><div><span>Cost / task</span><strong>${money(r.cost)}</strong></div><div><span>Output / task</span><strong>${compact(r.output)}</strong></div></div>`}
function overview(){const med=row('gpt-6-1-sol','medium'),old=row('gpt-6-sol','max'),son=row('claude-sonnet-5-5','max'),luna=row('gpt-6-luna','max'),mx=row('gpt-6-1-sol','max'),xh=row('gpt-6-1-sol','xhigh');const ss=seriesFor(state.scatterMetric);const sc=seriesFor('aa',available().filter(r=>['gpt-6-1-sol','gpt-6-sol'].includes(r.family)),true);const tax=(mx.cost/xh.cost-1)*100;
 return `<div class="stats">${stat('48 AA','6.1 Sol · Medium','Matches 6 Sol Max’s rounded index','#a590ff')}${stat(num((1-med.cost/old.cost)*100,0)+'% lower','Same headline score, less cost',money(med.cost)+' vs '+money(old.cost)+' per task','#73ddb3')}${stat(money(son.cost),'Sonnet 5.5 · Max','Full AA run: '+money(son.totalCost),'#ff7d9e')}${stat(money(luna.cost),'Luna · Max','37 AA at a very different price','#f7c762')}</div>
 <div class="grid grid-wide">${panel('The intelligence–cost frontier','Higher score. Lower cost. Dashed line: Pareto frontier among selected rows.',legend(ss)+chart(el=>scatter(el,ss,{xLabel:metricLabel(state.scatterMetric),xFormat:metricFormat(state.scatterMetric),log:state.log,yMin:10,yMax:60,frontier:true}))+inspector(),select('scatterMetric',[['cost','Cost / task'],['decode','Decode time'],['output','Output tokens'],['ttft','Time to first token'],['totalCost','Full AA cost']])+`<label><input type="checkbox" data-state="log" ${state.log?'checked':''}> Log x-axis</label>`)}${panel('A better staircase','6.1 pushes more performance into lower efforts.',legend(sc)+chart(el=>lines(el,sc,{yMin:20,yMax:60})))}</div>
 <div class="grid grid-table">${panel('Model comparison','Select an effort. Click a model to open head to head.',table(rowsAt(state.overviewEffort),[['model','Model'],['effort','Effort'],['aa','AA'],['cost','Cost / task'],['output','Output/task'],['firstAnswer','First answer']]),select('overviewEffort',effortOpts()))}<section class="panel insight"><div><h3>Max tax</h3><div class="big">+${num(tax,0)}%</div><p>6.1 Xhigh → Max task cost.<br><b>51 → 52</b> rounded AA points.</p></div><div><hr><p><b>${num(mx.output/xh.output,2)}× output tokens.</b><br>${num(mx.reasoning/xh.reasoning,2)}× reasoning tokens.<br>${num(mx.decode/xh.decode,2)}× estimated decode time.</p><a href="#scaling">Explore effort scaling</a></div></section></div>
 ${section('The comparisons that matter','Equal rounded indexes do not imply equal performance on each benchmark.')}<div class="more-comparisons">${panel('Medium inherited old Max','',`<div class="panel-body"><h3 style="color:var(--violet)">48 = 48</h3><p>6.1 Medium reaches 6 Sol Max’s headline index for ${money(med.cost)} rather than ${money(old.cost)} per task. Compare the benchmark profiles before treating them as interchangeable.</p><button data-preset="oldmax">Compare both</button></div>`)}${panel('Sonnet costs more than Opus','',`<div class="panel-body"><h3 style="color:var(--pink)">${money(son.cost)} vs ${money(row('claude-opus-5-5','max').cost)}</h3><p>At Max, Sonnet’s cheaper output price is overwhelmed by its much higher token use. List price alone misses the story.</p><button data-preset="claude">Compare both</button></div>`)}${panel('Luna’s sub-40 prison','',`<div class="panel-body"><h3 style="color:var(--mint)">37 AA · ${money(luna.cost)}</h3><p>Strong economics; uneven capabilities. Terminal-Bench and knowledge reliability hold it back. A 6.1 Luna uplift remains a hypothetical, with no announced model in this snapshot.</p><button data-preset="luna">Inspect Luna vs 6.1</button></div>`)}</div>`
}
const metricLabel=k=>({cost:'Cost per task (USD)',decode:'Estimated decode time (seconds)',output:'Output tokens per task',ttft:'Time to first token (seconds)',totalCost:'Full AA evaluation cost (USD)',reasoning:'Reasoning tokens per task',speed:'Output speed (tokens/s)',e2e:'500-token end-to-end time (seconds)',aa:'AA Intelligence Index'}[k]??k);
const metricFormat=k=>['cost','totalCost'].includes(k)?money:['output','reasoning'].includes(k)?compact:v=>num(v,0);
function effortSeries(k,rs=available()){return seriesFor('aa',rs,true).map(s=>({...s,points:s.points.map(p=>({...p,y:modelMap.get(p.id)[k]}))}))}
function scaling(){const ss=effortSeries(state.effortMetric),sols=available().filter(r=>['gpt-6-sol','gpt-6-1-sol'].includes(r.family));const delta=efforts.filter(e=>e!=='none').map(e=>({label:prettyEffort(e),value:row('gpt-6-1-sol',e).aa-row('gpt-6-sol',e).aa,color:'#a590ff'}));const transitions=[];for(const f of families.filter(f=>state.selected.has(f.id))){const rs=rowsAt('all').filter(r=>r.family===f.id);for(let i=1;i<rs.length;i++){let a=rs[i-1],b=rs[i];if(a.cost!=null&&b.cost!=null&&a.aa!=null&&b.aa!=null)transitions.push({model:f.name,color:f.color,effort:prettyEffort(a.effort)+' → '+prettyEffort(b.effort),aa:b.aa-a.aa,cost:b.cost-a.cost,output:b.output-a.output,decode:b.decode!=null&&a.decode!=null?b.decode-a.decode:null})}}
 return `<div class="grid">${panel('Intelligence by effort','Some tests peak before Max. The index is a rounded composite.',legend(ss)+chart(el=>lines(el,ss,{yLabel:metricLabel(state.effortMetric),yFormat:metricFormat(state.effortMetric),yMax:state.effortMetric==='aa'?60:undefined})),select('effortMetric',[['aa','AA Index'],['cost','Cost / task'],['output','Output tokens'],['reasoning','Reasoning tokens'],['decode','Decode time'],['ttft','First-token delay']]))}${panel('6 Sol → 6.1 Sol','Rounded index gain at the same effort. None is unsupported by 6.1.',chart(el=>bars(el,delta,{format:v=>'+'+num(v),label:'AA index point gain'})))}</div>
 <div class="grid">${panel('Cost scaling','Same token tariff at every effort; different usage.',legend(effortSeries('cost'))+chart(el=>lines(el,effortSeries('cost'),{yLabel:'USD per task',yFormat:money})))}${panel('Reasoning scaling','AA’s reasoning-token subset of total output.',legend(effortSeries('reasoning'))+chart(el=>lines(el,effortSeries('reasoning'),{yLabel:'Reasoning tokens per task',yFormat:compact})))}</div>
 ${panel('What the next effort costs','Marginal changes between adjacent measured settings; negative values are possible.',table(transitions,[['model','Model'],['effort','Transition'],['aa','Δ AA'],['cost','Δ $/task'],['output','Δ output tokens'],['decode','Δ decode seconds']]),'','full')}
 ${section('6.1 is not monotonically better','Every AA benchmark, every supported effort.')}${benchmarkTable(DATA.models.filter(r=>r.family==='gpt-6-1-sol').sort((a,b)=>efforts.indexOf(a.effort)-efforts.indexOf(b.effort)),DATA.benchmarks.slice(0,10))}
 <div class="notice"><p>More reasoning can improve some tasks and hurt others. On this run, Max trails Xhigh on AutomationBench-AA, trails High/Xhigh on SciCode and GDP.pdf, and trails Low on AA-LCR. These are measured differences, not proof that the rankings are statistically significant.</p></div>
 ${panel('A 6.1 Luna thought experiment','Hypothetical only: apply Sol’s rounded same-effort gains mechanically to Luna.',legend([{name:'Measured 6 Luna',color:'#73ddb3'},{name:'Hypothetical uplift',color:'#a590ff'}])+chart(el=>lines(el,[{name:'Measured',color:'#73ddb3',points:[21,29,32,34,37].map((v,i)=>({x:i,y:v,tip:labels[i+1]+': '+v+' AA (measured)'}))},{name:'Hypothetical',color:'#a590ff',points:[29,37,39,41,41].map((v,i)=>({x:i,y:v,tip:labels[i+1]+': '+v+' AA (hypothetical, not a real model)'}))}],{labels:labels.slice(1),yLabel:'AA Intelligence Index',yMax:50}))+`<p class="note">The resulting 29 / 37 / 39 / 41 / 41 ladder is arithmetic, not a prediction. There is no verified 6.1 Luna in this snapshot.</p>`,'','full')}${section('Sonnet 5 → Sonnet 5.5','Historical comparison from the same AA index version.')}<div class="grid">${panel('A huge capability jump','Sonnet 5 in gray; Sonnet 5.5 in pink. Current Low is incomplete.',legend([{name:'Sonnet 5',color:'#97a1b6'},{name:'Sonnet 5.5',color:'#ff7d9e'}])+chart(el=>lines(el,effortSeries('aa',DATA.models.filter(r=>r.family.startsWith('claude-sonnet-'))),{yMax:60})))}${panel('And a very different cost curve','The improvement is real. Max becomes materially more expensive.',chart(el=>lines(el,effortSeries('cost',DATA.models.filter(r=>r.family.startsWith('claude-sonnet-'))),{yLabel:'USD per task',yFormat:money})))}</div>`
}
function economics(){const rs=rowsAt(state.econEffort);const cb=rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),color:r.color,...r.costBreakdown}));const priceRows=mainFamilies.filter(f=>state.selected.has(f.id)).map(f=>row(f.id,'max'));return `<div class="controls"><label>Effort ${select('econEffort',effortOpts(true))}</label></div><div class="grid">${panel('Task cost','Weighted average across index benchmarks.',chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),value:r.cost,color:r.color})),{format:money,label:'USD per task'})))}${panel('Full evaluation spend','Total cost across all evaluations, excluding repeats.',chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),value:r.totalCost,color:r.color})),{format:money,label:'USD for the complete AA run'})))}</div>
 ${panel('Where the task cost goes','Answer + reasoning + fresh input + cache read + cache write.',legend([{name:'Answer',color:'#a590ff'},{name:'Reasoning',color:'#6451c7'},{name:'Fresh input',color:'#64d7f4'},{name:'Cache read',color:'#73ddb3'},{name:'Cache write',color:'#f7c762'}])+chart(el=>bars(el,cb,{keys:[{key:'answer',label:'Answer',color:'#a590ff'},{key:'reasoning',label:'Reasoning',color:'#6451c7'},{key:'nonCacheInput',label:'Fresh input',color:'#64d7f4'},{key:'cacheRead',label:'Cache read',color:'#73ddb3'},{key:'cacheWrite',label:'Cache write',color:'#f7c762'}],format:money,label:'USD per task by token type'})),'','full')}
 ${panel('The cache discount','Cached input savings relative to fresh input at standard token prices.',chart(el=>bars(el,priceRows.map(r=>({label:r.model,value:(1-r.cachePrice/r.inputPrice)*100,color:r.color})),{format:v=>num(v,0)+'%',label:'Cache-read discount (%)'})),'','full')}${section('API tariff','Standard short-context pricing, USD per million tokens.')}${panel('The underlying price','Effort changes token use, not the nominal tariff.',table(priceRows,[['model','Model'],['inputPrice','Input'],['cachePrice','Cache read'],['cacheWritePrice','Cache write'],['outputPrice','Output'],['blendedPrice','AA blended tariff'],['contextAA','AA context']]),'','full')}
 <div class="notice"><p>AA’s blended tariff uses a <b>7:2:1 cache-read / input / output mix</b>. It is not your workload’s actual price. OpenAI documents 1,050,000 context tokens and 128,000 maximum output tokens; AA lists 872k for 6 Sol and 1M for 6.1. Both measurements are retained with their source labels.</p></div>
 ${panel('Your cache economics','A token-price estimate for a fixed workload. This is separate from benchmark task cost.',`<div class="panel-body scenario"><div>${slider('input','Input tokens',1000,1050000,1000)}${slider('cache','Cached share (%)',0,100,1)}${slider('output','Generated tokens',1000,128000,1000)}${slider('calls','Number of requests',1,1000,1)}<label class="stacked">OpenAI processing ${select('service',[['standard','Standard'],['fast','Fast · 2×'],['batch','Batch / Flex · 0.5×']])}</label><p class="note">Cache reads are assumed already available. Excludes cache creation, tools and regional premiums. Above 272k input, OpenAI’s full request uses 2× input/cache and 1.5× output rates. Processing options here apply to OpenAI models only.</p></div><div id="scenario-chart"></div></div><div class="table-wrap" id="scenario-table"></div>`,'','full')}`}
function slider(k,label,min,max,step){return `<div class="controls"><div><div class="slider-label"><label for="${k}">${label}</label><output id="${k}-value">${num(state[k])}${k==='cache'?'%':''}</output></div><input id="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${state[k]}" data-slider="${k}"></div></div>`}
function scenario(){const rs=mainFamilies.filter(f=>state.selected.has(f.id)).map(f=>{let r=row(f.id,'max'),openai=f.id.startsWith('gpt'),long=openai&&state.input>272000,mode=openai?({standard:1,fast:2,batch:.5}[state.service]):1;let input=state.input*((1-state.cache/100)*r.inputPrice+state.cache/100*r.cachePrice)/1e6*(long?2:1),out=state.output*r.outputPrice/1e6*(long?1.5:1);return {model:f.name,color:f.color,label:f.name,input,output:out,cost:(input+out)*mode,totalCost:(input+out)*mode*state.calls,effort:long?'Long context':'Short context'}});if($('#scenario-chart')){bars($('#scenario-chart'),rs.map(r=>({...r,value:r.cost})),{format:money,label:'Estimated USD per request'});$('#scenario-table').innerHTML=table(rs,[['model','Model'],['effort','OpenAI price tier'],['cost','Per request'],['totalCost','All requests']])}}
function tokens(){const rs=rowsAt(state.tokenEffort);const ss=seriesFor('decode');const variation=rs.filter(r=>r.speedVariance);return `<div class="controls"><label>Effort ${select('tokenEffort',effortOpts(true))}</label></div><div class="grid">${panel('Output: answer vs reasoning','Reasoning is included in total output, not added to it.',legend([{name:'Answer',color:'#a590ff'},{name:'Reasoning',color:'#6451c7'}])+chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),answer:r.answer,reasoning:r.reasoning,color:r.color})),{keys:[{key:'answer',label:'Answer',color:'#a590ff'},{key:'reasoning',label:'Reasoning',color:'#6451c7'}],label:'Generated tokens per task'})))}${panel('Full-run output','Millions of tokens across the complete index evaluation.',chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),value:r.totalOutput,color:r.color})),{label:'Total output tokens'})))}</div>
 <div class="grid">${panel('The wait for an answer','Time to first answer token includes pre-answer thinking.',chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),value:r.firstAnswer,color:r.color})),{format:seconds,label:'Seconds before the first answer token'})))}${panel('Output speed','Throughput after the first response chunk.',chart(el=>bars(el,rs.map(r=>({label:r.model+' '+prettyEffort(r.effort),value:r.speed,color:r.color})),{format:v=>num(v,1)+' t/s',label:'Output tokens per second'})))}</div>
 <div class="grid">${panel('Intelligence vs decode time','AA’s estimated decode time excludes TTFT and overhead.',legend(ss)+chart(el=>scatter(el,ss,{xLabel:'Estimated decode time (seconds)',xFormat:v=>num(v)+'s',yMin:10,yMax:60})))}${panel('6.1’s latency cliff','User-copied performance snapshot, preserved exactly.',chart(el=>lines(el,[{name:'First answer',color:'#ff7d9e',points:DATA.models.filter(r=>r.family==='gpt-6-1-sol').map(r=>({x:efforts.indexOf(r.effort)-1,y:r.pastedPerformance.ttft,tip:prettyEffort(r.effort)+': '+seconds(r.pastedPerformance.ttft)}))}],{labels:labels.slice(1),yLabel:'Seconds to first answer',yFormat:v=>num(v)+'s'})))}</div>
 ${panel('Every latency measurement','TTFT, first answer, 500-token E2E and decode time are different metrics.',table(rs,[['model','Model'],['effort','Effort'],['speed','Tokens/s'],['ttft','TTFT'],['firstAnswer','First answer'],['e2e','500-token E2E'],['decode','Decode/task']]),'','full')}
 ${panel('Prompt length changes performance','Pick a variant to see AA’s prompt-specific measurements.',promptTable(modelMap.get(state.detailModel)),select('detailModel',DATA.models.map(r=>[r.id,r.model+' · '+prettyEffort(r.effort)])),'full')}
 ${panel('Speed & latency ranges','AA p05, q25, median, q75, p95. These are distribution percentiles, not confidence intervals.',varianceTable(variation),'','full')}`}
function promptTable(r){let p=r.promptTypes;if(!p)return '<div class="empty">No prompt-type breakdown available.</div>';return `<div class="table-wrap"><table><thead><tr><th>Prompt type</th><th>Output speed</th><th>TTFT</th><th>First answer</th><th>500-token E2E</th></tr></thead><tbody>${Object.entries(p).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${num(v.medianOutputSpeed,1)} t/s</td><td>${seconds(v.medianTimeToFirstChunk)}</td><td>${seconds(v.medianTimeToFirstAnswerToken)}</td><td>${seconds(v.medianEndToEndResponseTime)}</td></tr>`).join('')}</tbody></table></div>`}
function varianceTable(rs){return `<div class="table-wrap"><table><thead><tr><th>Model / effort</th><th>Metric</th>${['p05','q25','median','q75','p95'].map(x=>'<th>'+x+'</th>').join('')}</tr></thead><tbody>${rs.flatMap(r=>[['Speed (t/s)',r.speedVariance],['TTFT (s)',r.latencyVariance]].filter(([,v])=>v).map(([k,v])=>`<tr><td>${esc(r.model)} · ${prettyEffort(r.effort)}</td><td>${k}</td>${['p05','q25','median','q75','p95'].map(p=>'<td>'+num(v[p],1)+'</td>').join('')}</tr>`)).join('')}</tbody></table></div>`}
function benchmarkTable(rs,bs=DATA.benchmarks.slice(0,10)){return `<section class="panel full"><div class="table-wrap"><table class="heat-table"><thead><tr><th>Model / effort</th>${bs.map(b=>`<th title="${esc(b.description??b.label)}">${b.label}<br><span class="muted">${b.unit}</span></th>`).join('')}</tr></thead><tbody>${rs.map(r=>`<tr><td>${dot(r.color)} ${esc(r.model)} · ${prettyEffort(r.effort)}</td>${bs.map(b=>{let v=r.benchmarks[b.key],vals=rs.map(r=>r.benchmarks[b.key]).filter(v=>v!=null),min=Math.min(...vals),max=Math.max(...vals),t=v==null?0:(v-min)/(max-min||1),color=`rgb(${Math.round(28+110*t)} ${Math.round(37+79*t)} ${Math.round(60+175*t)})`;return `<td class="${v==null?'muted':'heat'}" style="background:${color}" data-tip="${esc(r.model+' · '+prettyEffort(r.effort)+'\n'+b.label+': '+bf(b.key,v))}">${bf(b.key,v)}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><div class="matrix-legend">Lower within column <i class="matrix-gradient"></i> Higher within column</div><p class="note" style="padding:0 20px 16px">Colors are normalized independently for each column among visible rows. Values keep their original units. Missing results stay blank. A darker cell is not necessarily poor in absolute terms.</p></section>`}
function capabilities(rs){return `<section class="panel full"><div class="table-wrap"><table><thead><tr><th>Model / effort</th>${DATA.capabilities.map(c=>'<th>'+c.label+'</th>').join('')}</tr></thead><tbody>${rs.map(r=>`<tr><td>${dot(r.color)} ${r.model} · ${prettyEffort(r.effort)}</td>${DATA.capabilities.map(c=>'<td>'+num(r.capabilities[c.key],1)+'</td>').join('')}</tr>`).join('')}</tbody></table></div></section>`}
function benchmarks(){const rs=rowsAt(state.benchEffort),b=DATA.benchmarks.find(b=>b.key===state.benchKey);const ss=families.filter(f=>state.selected.has(f.id)).map(f=>({name:f.name,color:f.color,points:available().filter(r=>r.family===f.id).sort((a,b)=>efforts.indexOf(a.effort)-efforts.indexOf(b.effort)).map(r=>({x:r.evalDetails[b.key]?.costPerTask,y:r.benchmarks[b.key],id:r.id,tip:`${r.model} · ${prettyEffort(r.effort)}\n${b.label}: ${bf(b.key,r.benchmarks[b.key])}\n${money(r.evalDetails[b.key]?.costPerTask)}/benchmark task\n${compact(r.evalDetails[b.key]?.outputTokensPerTask)} output tokens`}))}));return `<div class="controls"><label>Effort ${select('benchEffort',effortOpts(true))}</label></div>${section('The ten AA index evaluations','Primary composite ingredients; all higher is better.')}${benchmarkTable(rs)}
 ${section('Additional AA measurements','Not all are included in the headline index.')}${benchmarkTable(rs,DATA.benchmarks.filter(b=>b.extra))}
 ${panel('A benchmark’s own cost frontier','Benchmark-specific costs, rather than the composite weighted task cost.',legend(ss)+chart(el=>scatter(el,ss,{xLabel:b.label+' task cost (USD)',yLabel:b.label+' ('+b.unit+')',yFormat:v=>num(v,b.unit==='Elo'?0:1)})),select('benchKey',DATA.benchmarks.filter(b=>!b.extra).map(b=>[b.key,b.label])),'full')}
 ${section('Capability indexes','Domain composites are separate from raw benchmark scores.')}${capabilities(rs)}
 <div class="notice"><p>AA-Briefcase and GDPval are Elo ratings. AA-Omniscience is a −100 to 100 reliability index; <b>it is not accuracy</b>. “Non-hallucination” is 1 − AA’s hallucination rate. Refusals make it different from 1 − accuracy. CritPt is marked under review in the source.</p></div>`}
const presets={oldmax:['gpt-6-1-sol-medium','gpt-6-sol'],claude:['claude-sonnet-5-5','claude-opus-5-5'],luna:['gpt-6-luna','gpt-6-1-sol-low'],max:['gpt-6-1-sol-xhigh','gpt-6-1-sol'],astra:['gpt-6-1-sol','gpt-6-astra']};
function comparison(){let a=modelMap.get(state.compareA),b=modelMap.get(state.compareB),bcolor=a.family===b.family?'#64d7f4':b.color,opts=DATA.models.map(r=>[r.id,r.model+' · '+prettyEffort(r.effort)]),bs=DATA.benchmarks.slice(0,10);let delta=a.aa!=null&&b.aa!=null?a.aa-b.aa:null;let cheaper=a.cost!=null&&b.cost!=null?(1-a.cost/b.cost)*100:null;const summary=delta==null?'One selected model has no complete current AA result.':`<strong>${a.model} ${prettyEffort(a.effort)}</strong> scores ${delta>0?'+'+delta:delta} rounded AA points versus <strong>${b.model} ${prettyEffort(b.effort)}</strong>${cheaper!=null?`, at ${num(Math.abs(cheaper),0)}% ${cheaper>=0?'lower':'higher'} benchmark task cost`:''}.`;
 return `<div class="preset-buttons"><button data-preset="oldmax">6.1 Medium vs old Max</button><button data-preset="max">Xhigh vs Max</button><button data-preset="claude">Sonnet vs Opus</button><button data-preset="astra">6.1 vs Astra</button><button data-preset="luna">Luna vs 6.1 Low</button></div><div class="compare-pickers"><label>Model A ${select('compareA',opts)}</label><label>Model B ${select('compareB',opts)}</label></div><p class="comparison-summary">${summary}</p><div class="grid">${panel(a.model+' · '+prettyEffort(a.effort),'',compareMetrics(a))}${panel(b.model+' · '+prettyEffort(b.effort),'',compareMetrics(b))}</div>
 <div class="grid">${panel('Capability profile','Fixed 0–100 scale; missing domains are not replaced with zero.',legend([{name:a.model+' '+prettyEffort(a.effort),color:a.color},{name:b.model+' '+prettyEffort(b.effort),color:bcolor}])+chart(el=>radar(el,[a,b].map((r,i)=>({name:r.model+' '+prettyEffort(r.effort),color:i?bcolor:r.color,values:DATA.capabilities.map(c=>r.capabilities[c.key])})),DATA.capabilities)))}${panel('The output bill','Absolute generated tokens, with reasoning shown separately.',legend([{name:'Answer',color:'#a590ff'},{name:'Reasoning',color:'#6451c7'}])+chart(el=>bars(el,[a,b].map(r=>({label:r.model+' '+prettyEffort(r.effort),answer:r.answer,reasoning:r.reasoning,color:r.color})),{keys:[{key:'answer',label:'Answer',color:'#a590ff'},{key:'reasoning',label:'Reasoning',color:'#6451c7'}],label:'Tokens per task'})))}</div>
 ${panel('Benchmark by benchmark','Raw scores and differences; units remain separate.',`<div class="table-wrap"><table><thead><tr><th>Benchmark</th><th>${a.model} ${prettyEffort(a.effort)}</th><th>${b.model} ${prettyEffort(b.effort)}</th><th>A − B</th></tr></thead><tbody>${DATA.benchmarks.map(k=>{let av=a.benchmarks[k.key],bv=b.benchmarks[k.key],d=av!=null&&bv!=null?av-bv:null;return `<tr><td>${k.label}</td><td class="${d>0?'winner':''}">${bf(k.key,av)}</td><td class="${d<0?'winner':''}">${bf(k.key,bv)}</td><td>${d==null?'—':(d>0?'+':'')+num(d,1)+(k.unit==='%'?' pp':'')}</td></tr>`}).join('')}</tbody></table></div>`,'','full')}
 ${panel('Benchmark-specific economics','A model’s average cost can hide a costly benchmark.',`<div class="table-wrap"><table><thead><tr><th>Benchmark</th><th>A cost/task</th><th>B cost/task</th><th>A tokens/task</th><th>B tokens/task</th></tr></thead><tbody>${bs.map(k=>`<tr><td>${k.label}</td><td>${money(a.evalDetails[k.key]?.costPerTask)}</td><td>${money(b.evalDetails[k.key]?.costPerTask)}</td><td>${compact(a.evalDetails[k.key]?.outputTokensPerTask)}</td><td>${compact(b.evalDetails[k.key]?.outputTokensPerTask)}</td></tr>`).join('')}</tbody></table></div>`,'','full')}`}
function compareMetrics(r){return `<div class="panel-body metric-lines">${[['AA Intelligence Index',r.aa??'—'],['Cost / task',money(r.cost)],['Full AA run',money(r.totalCost)],['Output / task',compact(r.output)],['Reasoning / task',compact(r.reasoning)],['First answer',seconds(r.firstAnswer)],['Output speed',r.speed==null?'—':num(r.speed,1)+' t/s'],['Decode / task',seconds(r.decode)]].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div><p class="note" style="padding:0 20px 15px"><a href="${esc(r.source)}" target="_blank" rel="noopener noreferrer">AA source for this variant</a></p>`}
const launchColor=name=>name.includes('6.1')?'#a590ff':name.includes('Astra')?'#f7c762':name.includes('6 Sol')?'#64d7f4':name.includes('Opus')?'#ff926b':'#a6b3c9';
function launchSeries(spec,categorical=false){let names=[...new Set(spec.values.map(v=>v.modelLabel??v.model))];return names.map(n=>({name:n,color:launchColor(n),points:spec.values.filter(v=>(v.modelLabel??v.model)===n).sort((a,b)=>a.order-b.order).map(v=>({x:categorical?v.order:v.cost,y:v.score*100,tip:`${n} · ${v.effortLabel}\n${num(v.score*100,2)}%${v.cost!=null?'\n'+money(v.cost)+'/task':''}`}))}))}
function launchTable(spec){const names=[...new Set(spec.values.map(v=>v.modelLabel??v.model))];return `<div class="table-wrap"><table><thead><tr><th>Model · score / cost per task</th>${labels.slice(1).map(l=>'<th>'+l+'</th>').join('')}</tr></thead><tbody>${names.map(n=>`<tr><td>${dot(launchColor(n))} ${esc(n)}</td>${labels.slice(1).map(e=>{let v=spec.values.find(v=>(v.modelLabel??v.model)===n&&v.effortLabel===e);return '<td>'+(v?num(v.score*100,2)+'%'+(v.cost!=null?' / '+money(v.cost):''):'—')+'</td>'}).join('')}</tr>`).join('')}</tbody></table></div>`}
function launch(){let active=DATA.launch[+state.launchIndex],ss=launchSeries(active);return `<div class="notice"><p>These are <b>OpenAI’s launch measurements</b>, with their own harnesses and settings. AutomationBench 1.0.6 is different from AutomationBench-AA. Terminal-Bench Science has independent AA and provider results. Do not merge these with the AA index.</p></div><div class="controls"><label>Evaluation ${select('launchIndex',DATA.launch.slice(0,6).map((s,i)=>[i,s.title]))}</label></div>
 <div class="grid">${panel(active.title,active.lowerBetter?'Lower error rate and lower cost are better.':'Higher score and lower cost are better.',legend(ss)+chart(el=>scatter(el,ss,{xLabel:'Average API cost per task (USD)',yLabel:active.lowerBetter?'Error rate (%)':'Score (%)',yFormat:v=>num(v,1)+'%',yMax:active.lowerBetter?15:100})))}${panel('Effort scaling','Low → Medium → High → Xhigh → Max.',chart(el=>lines(el,launchSeries(active,true),{labels:labels.slice(1),yLabel:active.lowerBetter?'Error rate (%)':'Score (%)',yFormat:v=>num(v,1)+'%',yMax:active.lowerBetter?15:100})))}</div>
 ${section('Every launch result','Exact chart data, with score and average task cost.')}${DATA.launch.slice(0,6).map(spec=>panel(spec.title,spec.lowerBetter?'Lower is better.':'Higher is better.',launchTable(spec),'','full')).join('')}
 ${section('Reliability & alignment stress tests','Provider-specific evaluations on deliberately challenging situations.')}<div class="grid">${DATA.launch.slice(6).map(spec=>panel(spec.title,'Lower failure rate is better; settings vary across models.',chart(el=>bars(el,spec.values.map(v=>({label:(v.modelLabel??v.model)+' '+v.effortLabel,value:v.score*100,color:launchColor(v.modelLabel??v.model)})),{format:v=>num(v,2)+'%',label:'Failure rate (%)'})))).join('')}</div>
 <p class="note">The factuality set contains conversations where users had flagged an earlier model’s factual error; it is not typical usage. Fable’s reported AutomationBench cost excludes Opus fallback costs (~40% of tasks). Claude rows use the labeled fallback configuration. <a href="https://openai.com/index/introducing-gpt-6-1-sol/" target="_blank" rel="noopener noreferrer">Official launch page</a></p>`}
const extraCols=[['model','Model'],['effort','Effort'],['inputPrice','Input / M'],['cachePrice','Cache read / M'],['cacheWritePrice','Cache write / M'],['outputPrice','Output / M'],['blendedPrice','AA blend / M'],['contextAA','AA context'],['totalInput','Full input'],['totalReasoning','Full reasoning'],['totalAnswer','Full answer']];
function dataPage(){let rs=rowsAt(state.tableEffort).sort((a,b)=>{let av=a[state.sort],bv=b[state.sort];if(av==null)return 1;if(bv==null)return-1;return typeof av==='string'?av.localeCompare(bv)*state.sortDir:(av-bv)*state.sortDir});let r=modelMap.get(state.detailModel);return `<div class="controls"><label>Effort ${select('tableEffort',effortOpts(true))}</label><label>Columns ${select('tableCategory',[['core','Intelligence, costs & performance'],['pricing','Pricing, context & total tokens']])}</label><button id="download-csv">Export visible rows (CSV)</button><span class="dataset-count">${rs.length} variants shown · click column names to sort</span></div>${panel('The complete AA table','Missing values are unavailable, not zero.',table(rs,state.tableCategory==='core'?coreCols:extraCols,true),'','full')}
 ${section('Benchmark economics, expanded','Score, API cost, generated output, and estimated decode time.')}${panel('A variant’s full evaluation anatomy','Values refer to this benchmark’s tasks, not the composite average.',detailTable(r),select('detailModel',DATA.models.map(r=>[r.id,r.model+' · '+prettyEffort(r.effort)])),'full')}
 ${section('Capability indexes')}${capabilities(rs)}${section('All benchmark scores')}${benchmarkTable(rs,DATA.benchmarks)}
 ${panel('Sonnet 5.5 Low: prior snapshot','Earlier conversation numbers retained for continuity; the current AA result is incomplete.',`<div class="panel-body"><p>Earlier snapshot: <b>36 AA · $0.41/task · $544 full AA cost · 14k output/task · 5k reasoning/task · 23M full output</b>. These values are excluded from the current-data plots and Pareto frontier.</p><p class="note">The present source supplies some benchmark and performance fields, but no complete current Intelligence Index result or composite cost. The full dataset retains this earlier snapshot as a separate object.</p></div>`,'','full')}
 ${panel('Original GPT-6.1 copied performance snapshot','Preserved separately from the refreshed provider measurements.',`<div class="table-wrap"><table><thead><tr><th>Effort</th><th>Tokens/s</th><th>TTFT / first answer</th><th>500-token E2E</th><th>Decode/task</th></tr></thead><tbody>${DATA.models.filter(r=>r.family==='gpt-6-1-sol').sort((a,b)=>efforts.indexOf(a.effort)-efforts.indexOf(b.effort)).map(r=>`<tr><td>${prettyEffort(r.effort)}</td><td>${r.pastedPerformance.speed}</td><td>${seconds(r.pastedPerformance.ttft)}</td><td>${seconds(r.pastedPerformance.e2e)}</td><td>${seconds(r.pastedPerformance.decode)}</td></tr>`).join('')}</tbody></table></div>`,'','full')}
 ${panel('Machine-readable data','All 38 variants, detailed components, prompt-type measurements, and all ten launch chart datasets.',`<div class="panel-body"><button id="download-json-inline">Download complete JSON</button><details><summary>Inspect the selected variant’s full data</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details></div>`,'','full')}`}
function detailTable(r){return `<div class="table-wrap"><table><thead><tr><th>Evaluation</th><th>Score</th><th>Cost/task</th><th>Output/task</th><th>Decode/task</th><th>Weighted cost contribution</th></tr></thead><tbody>${DATA.benchmarks.filter(b=>!b.extra).map(b=>{let v=r.evalDetails[b.key];return `<tr><td>${b.label}</td><td>${bf(b.key,r.benchmarks[b.key])}</td><td>${money(v?.costPerTask)}</td><td>${compact(v?.outputTokensPerTask)}</td><td>${seconds(v?.timePerTask)}</td><td>${money(v?.costPerTask*({ 'aa-briefcase':.15,'gdpval-aa':.1,'automationbench-aa':.05,'terminalbench-4-0':.1,'scicode':.1,'humanitys-last-exam':.1,'gdp-pdf':.1,'critpt':.1,'omniscience':.15,'artificial-analysis-long-context-reasoning':.05 }[b.key]))}</td></tr>`}).join('')}</tbody></table></div><p class="note" style="padding:0 20px 16px">AA index cost weighting: Briefcase 15%, GDPval 10%, Automation 5%, Terminal 10%, SciCode 10%, HLE 10%, GDP.pdf 10%, CritPt 10%, Omniscience 15%, LCR 5%. Higher weighted contribution can come from either cost or benchmark weight.</p>`}
function sources(){const defs=[['Intelligence Index','AA v4.3.2 combines ten evaluations. The displayed index is rounded; the dataset also retains the unrounded composite. Small rounded differences should not be treated as proven superiority.'],['Cost per task','A weighted average of each benchmark’s cost per task. Includes fresh input, cache reads, cache writes, reasoning and answer tokens. It is not the full-run cost divided by one common task count.'],['Full AA cost','Total spend across the index evaluation, excluding repeats. The workload mixture differs from the weighted per-task statistic.'],['Output & reasoning','Total output already includes reasoning. Answer tokens are the other subset. Exact recovered values replace approximate subtraction of rounded k-token counts.'],['Decode time per task','AA estimates this from weighted output tokens and measured throughput. It excludes TTFT, setup, tool time and overhead. It is not a measured end-to-end completion duration.'],['TTFT / first answer / 500-token E2E','TTFT is the first response chunk. First-answer time accounts for pre-answer reasoning when applicable. E2E is a standardized 500-token response estimate, not a whole benchmark task.'],['Pareto frontier','A row belongs to this cost/score frontier if no other selected row has at least its score at no higher cost, with at least one strict improvement. The line changes with filters.'],['Heatmap color','Each benchmark column is normalized independently over the selected rows. Elo, percentages and reliability indexes are not placed on a single shared score scale.'],['Capability radar','AA’s domain composites use a fixed 0–100 radial scale. Missing domains remain missing, rather than becoming zero.'],['Price estimates','The cache calculator uses explicit input/output quantities and published token rates. It does not predict task success, actual token demand, tools or regional premiums.']];return `<div class="notice"><p><b>This is the September 29 release-day snapshot.</b> AA throughput measurements change independently of benchmark results. The original pasted 6.1 performance table remains available under All data; refreshed data is used elsewhere.</p></div>
 ${panel('Primary sources','All numerical views link back to the underlying measurements.',`<div class="panel-body"><div class="source-item"><div class="number">01</div><div><h3>Artificial Analysis</h3><p>Independent Intelligence Index v4.3.2, raw benchmark scores, economics, capability indexes and provider performance. Full chart data recovered from AA’s public comparison pages.</p>${families.map(f=>`<div class="faux-row">${dot(f.color)} <a href="https://artificialanalysis.ai/models/releases/${f.id}" target="_blank" rel="noopener noreferrer">${f.name} · all efforts</a></div>`).join('')}<p class="note"><a href="https://artificialanalysis.ai/methodology" target="_blank" rel="noopener noreferrer">AA methodology</a></p></div></div><div class="source-item"><div class="number">02</div><div><h3>Official OpenAI documentation</h3><p>Token prices, cache rules, long-context threshold, supported efforts, 1.05M context and 128k max output. 6.1 supports Low through Max; None is unavailable.</p><a href="https://developers.openai.com/api/docs/models/gpt-6.1-sol" target="_blank" rel="noopener noreferrer">GPT-6.1 Sol specifications</a> · <a href="https://developers.openai.com/api/docs/pricing" target="_blank" rel="noopener noreferrer">API pricing</a></div></div><div class="source-item"><div class="number">03</div><div><h3>OpenAI’s 6.1 launch evaluations</h3><p>All ten native chart datasets, including DeepSWE, GDP.pdf, AutomationBench 1.0.6, OSWorld 2.0 offline, Terminal-Bench Science, factuality and four alignment stress tests. Provider results retain their own methodology.</p><a href="https://openai.com/index/introducing-gpt-6-1-sol/" target="_blank" rel="noopener noreferrer">Official launch article</a></div></div><div class="source-item"><div class="number">04</div><div><h3>Anthropic pricing & fallback configuration</h3><p>Sonnet 5.5: $2 input / $10 output / $0.20 cache reads. Opus 5.5: $4 / $20 / $0.20. AA’s Claude 5.5 results use adaptive reasoning with default fallbacks, as labeled by AA.</p><a href="https://www.anthropic.com/claude-sonnet-5-5" target="_blank" rel="noopener noreferrer">Anthropic launch & pricing</a></div></div><div class="source-item"><div class="number">05</div><div><h3>Your pasted AA comparison</h3><p>The supplied Pasted text(3).txt preserves GPT-6.1’s effort table, rounded costs/tokens, first-token delay and throughput exactly as seen in the earlier conversation. It supplies the separate original performance snapshot.</p><p class="note">Historical Sonnet 5.5 Low figures are explicitly isolated. A hypothetical 6.1 Luna is not added as a real model.</p></div></div></div>`,'','full')}
 ${section('Definitions & comparison limits')}<dl class="definition-grid">${defs.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>
 ${section('Coverage')}<div class="stats">${stat('32','Current effort variants','Across the six central families','#a590ff')}${stat('6','Historical Sonnet 5 variants','Available alongside current models','#97a1b6')}${stat('18','AA benchmark fields','Ten index ingredients + eight extras','#73ddb3')}${stat('10','Official launch charts','Including factuality and stress tests','#f7c762')}</div><p class="note">Snapshot retrieval: ${esc(DATA.retrievedAt)}. This page uses a local fixed dataset; opening it does not automatically refresh benchmark results.</p>`}
function render(){chartJobs=[];chartId=0;const view=navItems.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'overview';state.view=view;$('#navigation').innerHTML=navItems.map(([id,label,path])=>`<a href="#${id}" class="${id===view?'active':''}" ${id===view?'aria-current="page"':''}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${path}"/></svg>${label}</a>`).join('');let [title,sub]=titles[view];$('#page-header').innerHTML=`<div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="snapshot"><div><span>Snapshot</span><b>Sep 29, 2026</b></div><div><span>Families</span><b>6 + history</b></div><div><span>Effort variants</span><b>32 + 6</b></div></div>`;$('#family-controls').hidden=['sources','launch','compare'].includes(view);$('#family-controls').innerHTML=families.map(f=>`<button data-family="${f.id}" aria-pressed="${state.selected.has(f.id)}">${dot(f.color)}${f.name}${f.legacy?' · history':''}</button>`).join('')+'<button class="reset" id="reset-families">Reset models</button>';$('#content').innerHTML=({overview,scaling,economics,tokens,benchmarks,compare:comparison,launch,data:dataPage,sources}[view])();chartJobs.forEach(job=>job());if(view==='economics')scenario();$('#tooltip').hidden=true;document.title=titles[view][0]+' — Model Atlas'}
function download(content,type,name){let u=URL.createObjectURL(new Blob([content],{type}));let a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const downloadJSON=()=>download(JSON.stringify(DATA,null,2),'application/json','model-atlas-2026-09-29.json');
function downloadCSV(){const rs=rowsAt(state.tableEffort),cols=[...new Set([...coreCols,...extraCols].map(([k])=>k))];let line=vals=>vals.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',');download([line(cols),...rs.map(r=>line(cols.map(k=>r[k])))].join('\r\n'),'text/csv;charset=utf-8','model-atlas-visible-rows.csv')}
function preset(k){[state.compareA,state.compareB]=presets[k];if(location.hash==='#compare')render();else location.hash='compare'}
function chartPoint(id){if(!modelMap.has(id))return;if(state.view==='overview'){state.inspector=id;$('#point-inspector').outerHTML=inspector()}else{state.compareA=id;location.hash='compare'}}
document.addEventListener('click',e=>{let b=e.target.closest('button,[data-point]');if(!b)return;if(b.dataset.family){let f=b.dataset.family;if(state.selected.has(f))state.selected.delete(f);else state.selected.add(f);render()}else if(b.id==='reset-families'){state.selected=new Set(mainFamilies.map(f=>f.id));render()}else if(b.dataset.preset)preset(b.dataset.preset);else if(b.dataset.compareModel){state.compareA=b.dataset.compareModel;location.hash='compare'}else if(b.dataset.point)chartPoint(b.dataset.point);else if(b.dataset.sort){state.sortDir=state.sort===b.dataset.sort?-state.sortDir:1;state.sort=b.dataset.sort;render()}else if(['download-json','download-json-inline'].includes(b.id))downloadJSON();else if(b.id==='download-csv')downloadCSV();else if(b.id==='menu-toggle'){let open=$('#sidebar').classList.toggle('open');b.setAttribute('aria-expanded',open)}});
document.addEventListener('change',e=>{let k=e.target.dataset.state;if(k){state[k]=e.target.type==='checkbox'?e.target.checked:e.target.value;render()}});
document.addEventListener('input',e=>{let k=e.target.dataset.slider;if(k){state[k]=+e.target.value;$('#'+k+'-value').textContent=num(state[k])+(k==='cache'?'%':'');scenario()}});
const tip=$('#tooltip');function showTip(target,x,y){if(!target?.dataset.tip){tip.hidden=true;return}tip.textContent=target.dataset.tip;tip.hidden=false;tip.style.left=Math.max(8,Math.min(x+16,innerWidth-tip.offsetWidth-12))+'px';tip.style.top=Math.max(8,Math.min(y+15,innerHeight-tip.offsetHeight-12))+'px'}
document.addEventListener('pointermove',e=>showTip(e.target.closest('[data-tip]'),e.clientX,e.clientY));document.addEventListener('focusin',e=>{let t=e.target.closest('[data-tip]');if(t){let r=t.getBoundingClientRect();showTip(t,r.x,r.y)}});document.addEventListener('focusout',()=>tip.hidden=true);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.point){e.preventDefault();chartPoint(e.target.dataset.point)}if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded',false);tip.hidden=true}});
window.addEventListener('hashchange',()=>{$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded',false);window.scrollTo(0,0);render()});let rt;window.addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(render,150)});render();
